### ISSUE TITLE
Tag for 0.0.1

### ISSUE THREAD

**Issue by dometec** [ngutils/cr-session#1]
Hi Gabriele, 
 could you please add the tag 0.0.1, it needed when I use bower update.

Thanks,
Domenico

**Comment by gianarb** [comment]
I @dometec now I have not a PC but I agree with you.. This package is ready to tag.. I added it in my todo list

Thanks for your feedback!

**Comment by gianarb** [comment]
Done.
https://github.com/ngutils/cr-session/releases/tag/0.1.0

Thanks a lot!
